version: 1

frontend:
  phases:
    preBuild:
      commands:
        - echo "Files in the current directory:$(pwd)"
        - ls -al
        - echo "-----------------------------"
        - npm install -g typescript
        - echo Installing source NPM dependencies...
        - npm ci
        - echo Installing client NPM dependencies...
        - npm run client-install
    build:
      commands:
        - echo Build started on `date`
        - echo Transpiling TypeScript client code...
        - npm run build:client
        - echo "Files in the current directory:$(pwd)"
        - ls -al
        - echo "-----------------------------"
    post_build:
      commands:
        - echo Build completed on `date`
  artifacts:
    baseDirectory: "."
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
