version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - echo Installing client NPM dependencies...
      - npm run client-install
      - echo Installing server NPM dependencies...
      - npm run server-install
  pre_build:
    commands:
      - echo Prebuild step...
      - echo Transpiling TypeScript server code...
      - npm run build:server
  build:
    commands:
      - echo Build started on `date`
      - echo Building the client...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
